name: SCHEDULED WORKFLOW 13 5 7 10 *
on:
    schedule:
        - cron: "13 5 7 10 *"
    workflow_dispatch:

jobs:
    run:
        name: Run
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.TOKEN }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.4.0
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm install

            - name: Run
              run: "node __generated-js/1.js token: ${{ secrets.BOT_TOKEN }} --trace-warnings --harmony"
