name: SCHEDULED WORKFLOW 50 0 * * *
on:
    schedule:
        - cron: "50 0 * * *"
    workflow_dispatch:

env:
    cron: "50 0 * * *"
    token: ${{ secrets.BOT_TOKEN }}

jobs:
    run:
        name: Run
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.TOKEN }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: "16.13.0"
                  cache: "npm"

            - name: Install
              run: npm install

            - name: Run
              run: node src/run.js

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.15.4
              with:
                  commit_message: "Updates from 50 0 * * *"
                  branch: ${{ github.head_ref }}
