name: QOTD
on:
    schedule:
        - cron: "0 12 * * *"
    workflow_dispatch:

jobs:
    run:
        name: Run
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.TOKEN }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.3.0
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm install

            - name: Run
              run: "node qotd/index.js token: ${{ secrets.BOT_TOKEN }} --trace-warnings --harmony"

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.14.1
              with:
                  commit_message: "Remove QOTD"
                  branch: ${{ github.head_ref }}
